on: push
name: test-and-build
jobs:
  build:
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.16
      uses: actions/setup-go@v1
      with:
        go-version: 1.16
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v1
      
    - name: Get dependencies
      run: |
        go mod download

    - name: Run unit-tests
      run: |
        GO111MODULE=on CGO_ENABLED=0 go test ./...

    - name: Build executables
      run: |
        ./build.sh

    - name: Upload artifact
      uses: actions/upload-artifact@v1.0.0
      with:
        name: binaries
        path: .build