on:
  release:
    types: [published]
name: handle-release
jobs:
  artifacts:
    name: Create and upload release artifacts
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go 1.16
        uses: actions/setup-go@v1
        with:
          go-version: 1.16
        id: go

      - name: Check out code at release tag
        uses: actions/checkout@v1
        with:
          ref: ${{ github.ref }}
          fetch-depth: 1

      - name: Get dependencies
        run: |
          go mod download

      - name: Build executables
        run: |
          ./build.sh

      - name: Create artifact archives
        run: |
          ./create-artifacts.sh

      - name: Upload artifacts archives
        uses: skx/github-action-publish-binaries@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          args: './.release/*'